extends Node2D
## Base script for all game rooms.
## Generates the floor and walls, locks the camera to a single screen,
## and positions the player at the correct spawn point on entry.
##
## Node convention in each room's .tscn:
##   TileMapLayer        — receives the floor generated by code
##   PuntosSpawn/        — Node2D with children: SpawnNorte, SpawnSur, SpawnEste, SpawnOeste
##   Enemigos/           — enemy instances for the room
##   Puertas/            — Door.tscn instances
##   Player              — Player.tscn instance (initial position: room center)
##   HealthUI            — HealthUI.tscn instance

@onready var _tilemap:    TileMapLayer = $TileMapLayer
@onready var _health_ui:  CanvasLayer  = $HealthUI

func _ready() -> void:
	## Connect before SceneManager can emit room_entered
	EventBus.room_entered.connect(_on_room_entered)
	_generate_floor()
	_generate_walls()
	_setup_camera_limits()
	## call_deferred guarantees Player._ready() has already run and registered with GameManager
	call_deferred("_setup_ui")

# ─── Room generation ──────────────────────────────────────────────────────────

func _generate_floor() -> void:
	## If the TileMap already has a tileset assigned in the editor, respect it.
	if _tilemap.tile_set:
		return
	## Use the real tileset. The grass tile occupies the top-left corner (atlas 0,0).
	var tex := load("res://assets/sprites/world/tileset_forest.png") as Texture2D
	var ts := TileSet.new()
	ts.tile_size = Vector2i(Constants.TILE_SIZE, Constants.TILE_SIZE)
	var src := TileSetAtlasSource.new()
	src.texture = tex
	src.texture_region_size = Vector2i(Constants.TILE_SIZE, Constants.TILE_SIZE)
	src.create_tile(Vector2i.ZERO)
	var src_id := ts.add_source(src)
	_tilemap.tile_set = ts
	for x in range(-Constants.ROOM_HALF_TILES_X, Constants.ROOM_HALF_TILES_X):
		for y in range(-Constants.ROOM_HALF_TILES_Y, Constants.ROOM_HALF_TILES_Y):
			_tilemap.set_cell(Vector2i(x, y), src_id, Vector2i.ZERO)

func _generate_walls() -> void:
	## Four invisible walls around the room using a single StaticBody2D.
	var hw := Constants.ROOM_HALF_TILES_X * Constants.TILE_SIZE   # 160 px
	var hh := Constants.ROOM_HALF_TILES_Y * Constants.TILE_SIZE   # 96 px
	var t  := 8.0  # half-thickness of each wall
	var body := StaticBody2D.new()
	body.name = "Paredes"
	add_child(body)
	## [center_x, center_y, half_width, half_height]
	var segmentos: Array = [
		[0.0,      -(hh + t), hw + t, t],   # north
		[0.0,       (hh + t), hw + t, t],   # south
		[-(hw + t), 0.0,      t, hh + t],   # west
		[ (hw + t), 0.0,      t, hh + t],   # east
	]
	for s in segmentos:
		var cs   := CollisionShape2D.new()
		var rect := RectangleShape2D.new()
		rect.size = Vector2(s[2] * 2.0, s[3] * 2.0)
		cs.shape    = rect
		cs.position = Vector2(s[0], s[1])
		body.add_child(cs)

func _setup_camera_limits() -> void:
	## Lock the camera exactly to the viewport for a single-room effect (no scroll).
	var camera := get_viewport().get_camera_2d()
	if not camera:
		return
	camera.limit_left   = -Constants.VIEWPORT_HALF_W
	camera.limit_right  =  Constants.VIEWPORT_HALF_W
	camera.limit_top    = -Constants.VIEWPORT_HALF_H
	camera.limit_bottom =  Constants.VIEWPORT_HALF_H

# ─── UI ───────────────────────────────────────────────────────────────────────

func _setup_ui() -> void:
	var player := GameManager.get_player()
	if not player:
		return
	var health := player.get_node_or_null("HealthComponent") as HealthComponent
	if not health:
		return
	_health_ui.setup(health.max_health)
	## Sync the UI with current health (important if coming from another room with damage)
	EventBus.player_health_changed.emit(health.current_health, health.max_health)

# ─── Spawn ────────────────────────────────────────────────────────────────────

func _on_room_entered(spawn_id: String) -> void:
	## Find the PuntosSpawn/SpawnXxx node and move the player there.
	## spawn_id = "norte", "sur", "este", "oeste" → node = "SpawnNorte", "SpawnSur", etc.
	var puntos := get_node_or_null("PuntosSpawn")
	if not puntos:
		push_warning("Room: node 'PuntosSpawn' does not exist.")
		return
	var nombre := "Spawn" + spawn_id.capitalize()
	var punto  := puntos.get_node_or_null(nombre)
	if not punto:
		push_warning("Room: spawn point '%s' not found in PuntosSpawn." % nombre)
		return
	var player := GameManager.get_player()
	if player:
		player.global_position = punto.global_position
